Some improvements in lradc GUI sysupgrade

diff --git a/package/base-files/files/sbin/sysupgrade b/package/base-files/files/sbin/sysupgrade
--- a/package/base-files/files/sbin/sysupgrade
+++ b/package/base-files/files/sbin/sysupgrade
@@ -1,32 +1,113 @@
 #!/bin/sh
-read -p "WARNING: you can loose Linux on your device. All your configs will be erased, save them. Make sure if you have an verified /tmp/sysupgrade_RTU968.tar !!! Don't turn off the device. Want to continue?(YES/n): " -n 3 -r
-echo    # (optional) move to a new line
+MODETEST=0
+try_upgrade ()
+{
+	VER_STRING=$(fw_printenv ver | awk -F 'Build TELEOFIS ' '{print $2}')
+	VER_FIRST=$(echo $VER_STRING | awk -F '.' '{print $1}')
+	VER_SECOND=$(echo $VER_STRING | awk -F '.' '{print $2}')
+	VER_THIRD=$(echo $VER_STRING | awk -F '.' '{print $3}')
+
+	if  [[ $VER_FIRST == ${VER_FIRST//[^0-9]/} ]] && [[ $VER_SECOND == ${VER_SECOND//[^0-9]/} ]] && [[ $VER_THIRD == ${VER_THIRD//[^0-9]/} ]]
+	then
+		# sophisticated bootloader check (caused by bugs in early versions)
+		if [ "$VER_FIRST" -eq 0 ]
+		then
+	        echo "Bootloader is too old"	# 0.x.x
+	        exit 1
+		fi
+
+		if [ "$VER_FIRST" -eq 1 ]
+		then
+			if  [ "$VER_SECOND" -eq 0 ]
+			then
+				echo "Bootloader is too old"	# 1.0.x
+	        	exit 1
+			fi
+
+			if  [ "$VER_SECOND" -eq 1 ]
+			then
+				if  [ "$VER_THIRD" -eq 0 ]
+		        then
+		            echo "Bootloader is too old" # 1.1.0
+		            exit 1
+		    	fi
+			fi
+		fi
+
+	    #### if bootloader is suitable:
+	    cd /tmp/
+		if [ ! -f /tmp/sysupgrade_RTU968.tar ]; 
+		then
+	    	echo "Sysupgrade file not found!"
+		else
+
+
+			### if we have an upgrade archive
+			tar -xf sysupgrade_RTU968.tar
+			if [ ! -f rootfs.img ] || [ ! -f openwrt-mxs-uImage ] || [ ! -f fdt.dtb ]; 
+			then
+		    	echo "Upgrade archive is corrupted"
+		    	exit 1
+		    fi
+		    ## if we have all upgrade files
+		    # if test mode
+		    if [ "$MODETEST" -eq 1 ]
+			then
+				rm rootfs.img
+				rm openwrt-mxs-uImage
+				rm fdt.dtb
+				echo OK
+				exit 0
+			fi
+			#
+			mtd erase updroot
+			mtd write rootfs.img  updroot
+			fw_setenv filesize_rootfs $(printf %x $(stat -c %s rootfs.img))
+			mtd erase kernel
+			mtd write openwrt-mxs-uImage kernel
+			mtd verify openwrt-mxs-uImage kernel
+			fw_setenv filesize_kernel $(printf %x $(stat -c %s openwrt-mxs-uImage))
+			mtd erase fdt
+			mtd write fdt.dtb fdt
+			mtd verify fdt.dtb fdt
+			fw_setenv filesize_fdt $(printf %x $(stat -c %s fdt.dtb))
+			fw_setenv update_flag 15963
+			reboot -f
+			##
+			###
+		fi
+		####
+	else
+	        echo "Can't read bootloader version:"
+	        fw_printenv ver
+	fi
+}
+
+# check -key options
+while getopts "yt" opt; do
+	case $opt in
+		y)
+			try_upgrade
+			exit 0
+			;;
+		t)
+			MODETEST=1
+			try_upgrade
+			exit 0
+			;;
+		\?)
+			echo "Invalid option: -$OPTARG" >&2
+			exit 1
+			;;
+	esac
+done
+
+# without options
+read -p "WARNING: All your configs will be erased, backup them. Don't turn off the device. Continue?(YES/n): " -n 3 -r
+echo	# move to a new line
 if [[ $REPLY == 'YES' ]]
 then
-
-	cd /tmp/
-	if [ ! -f /tmp/sysupgrade_RTU968.tar ]; 
-	then
-    		echo "Sysupgrade file not found!"
-	else
-		tar -xvf sysupgrade_RTU968.tar
-		mtd erase updroot
-		mtd write rootfs.img  updroot
-		mtd verify rootfs.img updroot
-		fw_setenv filesize_rootfs $(printf %x $(stat -c %s rootfs.img))
-		mtd erase kernel
-		mtd write openwrt-mxs-uImage kernel
-		mtd verify openwrt-mxs-uImage kernel
-		fw_setenv filesize_kernel $(printf %x $(stat -c %s openwrt-mxs-uImage))
-		mtd erase fdt
-		mtd write fdt.dtb fdt
-		mtd verify fdt.dtb fdt
-		fw_setenv filesize_fdt $(printf %x $(stat -c %s fdt.dtb))
-		fw_setenv update_flag 15963
-		reboot
-	fi
-
+	try_upgrade				
 else
-	printf "System Upgrade was cancelled. If you want to do it, plaese, print \"YES\" next time\n"
-
+	printf "System Upgrade was cancelled. If you want to do it, please, print \"YES\" next time"
 fi
